# unsecure converter
# 题目描述
# What the shell converter is this.
# n1book{c18e76558cb0fdb93746c1c331500eac}
version: "3.2"

services:
  converter:
    image: registry.cn-hangzhou.aliyuncs.com/n1book/web-crypto-padding:latest
    ports:
      - 80:1234